### ISSUE TITLE
Schema Design + ActiveRecord Associations

### ISSUE THREAD

**Issue by alexkahn** [alexkahn/reservator#3]
@carolineartz I've got some traction on this database business but any advice would totally rock!

**Comment by carolineartz** [comment]
@alexkahn nice!! Things look good. We can talk about your associations for categories and restaurants this afternoon. You add `has_many :through` associations, but you created the join table holding only foreign keys for these models, as you would for a `has_and_belongs_to_many` association (though the table would need to be called `categories_restaurants`, or flagged with the `:join_table` option to specify a non-standard naming for that table since c comes before r). :)

**Comment by alexkahn** [comment]
fixed in https://github.com/alexkahn/reservator/commit/fb05763c3c3503fc8dfcbb3c1992490a2100ea71
